import Script from "next/script";

export default function SEO() {

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    name: "The Bradley Group LLC",
    description:
      "Forensic economic consulting and expert witness services for litigation support",
    url: "https://the-bradley-group.com",
    logo: "https://the-bradley-group.com/tbg-logo.svg",
    image: "https://the-bradley-group.com/cover-photo.jpg",
    priceRange: "$1,500-$2,500",
    address: {
      "@type": "PostalAddress",
      addressCountry: "US",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "43.0731",
      longitude: "-89.4012",
    },
    telephone: "+1-608-218-4166",
    email: "info@the-bradley-group.com",
    sameAs: ["https://www.linkedin.com/company/the-bradley-group-llc"],
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: "Forensic Economic Services",
      itemListElement: [
        {
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            name: "Business Valuation",
            description:
              "Report of the expected future cash flows to be generated by a small-to-medium business (SMB).",
          },
        },
        {
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            name: "Personal Injury Economic Analysis",
            description:
              "Economic impact report evaluating the present value of diminished earning capacity, future medical care & expenses, and household services",
          },
        },
        {
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            name: "Wrongful Death Economic Analysis",
            description:
              "Economic impact report evaluating the present value of lost financial support and family services",
          },
        },
        {
          "@type": "Offer",
          itemOffered: {
            "@type": "Service",
            name: "Employment Termination Analysis",
            description:
              "Economic impact report evaluating the loss of earnings and benefits",
          },
        },
      ],
    },
    founder: {
      "@type": "Person",
      name: "Bradley Gibbs",
      jobTitle: "Forensic Economist",
      alumniOf: [
        {
          "@type": "EducationalOrganization",
          name: "University of Wisconsin Law School",
        },
        {
          "@type": "EducationalOrganization",
          name: "University of Wisconsin School of Business",
        },
      ],
    },
  };

  const faqStructuredData = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is a forensic economist?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "A forensic economist is an expert who applies economic theories and methods to calculate economic damages in legal cases. They analyze lost earnings, benefits, household services, and other economic losses resulting from personal injury, wrongful death, or employment disputes.",
        },
      },
      {
        "@type": "Question",
        name: "When should I hire a forensic economist?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "You should consider hiring a forensic economist early in the litigation process when your case involves claims for economic damages. This includes personal injury cases with lost earnings, wrongful death cases, employment disputes, or commercial litigation involving lost profits.",
        },
      },
      {
        "@type": "Question",
        name: "What types of damages can a forensic economist calculate?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "A forensic economist can calculate various types of economic damages including: lost past and future earnings, lost employment benefits, lost household services, future medical expenses, lost business profits, and the present value of future economic losses.",
        },
      },
    ],
  };

  return (
    <>
      <Script
        id="structured-data"
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(structuredData),
        }}
      />
      <Script
        id="faq-structured-data"
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(faqStructuredData),
        }}
      />
    </>
  );
}
